AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that calls the Lambda API.
Globals:
  Api:
    EndpointConfiguration: REGIONAL
Resources:
  JavaLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: org.virosms.lectorversomicro.LambdaStreamHandler::handleRequest
      Runtime: java21
      Description: Java function
      MemorySize: 512
      Timeout: 60
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      # Function's execution role
      Tracing: Active

